function getChar(charName) {
    switch (charName) {
    case "user" : return "\uf007"
    case "key" : return "\uf084"
    case "signin" : return "\uf090"
    case "remove" : return "\uf00d"
    case "shareAlt" : return "\uf064"
    case "barChart" : return "\uf080"
    case "thList" : return "\uf00b"
    case "cog" : return "\uf013"
    case "cogs" : return "\uf085"
    case "signOut" : return "\uf08b"
    case "_528" : return "\uf233"
    case "ellipsisVerticaL" : return "\uf142"
    case "building" : return "\uf0f7"
    case "truck" : return "\uf0d1"
    case "_413" : return "\uf1b8"
    case "alignJustify" : return "\uf039"
    case "save" : return "\uf0c7"
    case "removeSign" : return "\uf057"
    case "check" : return "\uf046"
    case "checkEmpty" : return "\uf096"
    case "ok" : return "\uf00c"
    case "folderOpen" : return "\uf0c7"
    case "_529" : return "\uf234"
    case "_530" : return "\uf235"
    case "questionSign" : return "\uf059"
    case "uploadAlt" : return "\uf093"
    case "downloadAlt" : return "\uf019"
    case "caretDown" : return "\uf0d7"
    case "globe" : return "\uf0ac"
    case "cut" : return "\uf0c4"
    case "copy" : return "\uf0c5"
    case "paste" : return "\uf0ea"
    case "undo" : return "\uf0e2"
    case "repeat" : return "\uf01e"
    case "exchange" : return "\uf0ec"
    case "arrowUp" : return "\uf062"
    case "longArrowLeft" : return "\uf177"
    case "longArrowRight" : return "\uf178"
    default : return ""
    }
}
