function getChar(charName) {
    switch (charName) {
    case "user" : return "\uf007"
    case "key" : return "\uf084"
    case "sign-in" : return "\uf090"
    case "remove" : return "\uf00d"
    case "times" : return "\uf00d"
    case "share" : return "\uf064"
    case "bar-chart" : return "\uf080"
    case "th-list" : return "\uf00b"
    case "cog" : return "\uf013"
    case "cogs" : return "\uf085"
    case "sign-out" : return "\uf08b"
    case "server" : return "\uf233"
    case "ellipsis-v" : return "\uf142"
    case "building" : return "\uf0f7"
    case "truck" : return "\uf0d1"
    case "recycl" : return "\uf1b8"
    case "align-justify" : return "\uf039"
    case "save" : return "\uf0c7"
    case "times-circle" : return "\uf057"
    case "check-square-o" : return "\uf046"
    case "square-o" : return "\uf096"
    case "check" : return "\uf00c"
    case "folder-open" : return "\uf0c7"
    case "user-plus" : return "\uf234"
    case "user-times" : return "\uf235"
    case "question-circle" : return "\uf059"
    case "upload" : return "\uf093"
    case "download" : return "\uf019"
    case "caret-down" : return "\uf0d7"
    case "globe" : return "\uf0ac"
    case "cut" : return "\uf0c4"
    case "scissors" : return "\uf0c4"
    case "copy" : return "\uf0c5"
    case "files-o" : return "\uf0c5"
    case "paste" : return "\uf0ea"
    case "clipboard" : return "\uf0ea"
    case "undo" : return "\uf0e2"
    case "repeat" : return "\uf01e"
    case "exchange" : return "\uf0ec"
    case "arrow-up" : return "\uf062"
    case "long-arrow-left" : return "\uf177"
    case "long-arrow-right" : return "\uf178"
    case "bell" : return "\f0f3"
    case "bell-o" : return "\f0a2"
    case "bell-splash" : return "\f1f6"
    case "bell-splash-o" : return "\f1f7"
    case "exclamation-triangle" : return "\uf071"
    default : return ""
    }
}
